[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm ci --workspace=shared --workspace=server']

[phases.build]
cmds = ['npm run build --workspace=shared']

[start]
cmd = 'npm run start --workspace=server'